/**
 * Generate the web's CSS custom properties from the shared token source.
 *
 * packages/shared/src/tokens.json is the single source of truth for colours,
 * scrims and shadows; native reads it through `@getsu/shared`, and the web
 * reads the file this script writes. Run via `npm run tokens` (build and dev
 * both do it for you).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'packages/shared/src/tokens.json');
const out = join(root, 'apps/web/src/tokens.generated.css');

const cssVarName = (token) => `--${token.replace(/([a-z])([A-Z0-9])/g, '$1-$2').toLowerCase()}`;

const block = (tokens) =>
  Object.entries(tokens)
    .map(([name, value]) => `  ${cssVarName(name)}: ${value};`)
    .join('\n');

const { light, dark } = JSON.parse(readFileSync(src, 'utf8'));

const css = `/* Generated by scripts/gen-tokens.mjs from packages/shared/src/tokens.json.
   Do not edit by hand — edit the JSON and run \`npm run tokens\`. */

:root {
${block(light)}
}

[data-theme='dark'] {
${block(dark)}
}
`;

const previous = (() => { try { return readFileSync(out, 'utf8'); } catch { return null; } })();
if (previous !== css) writeFileSync(out, css);
console.log(`tokens → ${out.replace(`${root}/`, '')}`);
